const translations = {
  id: {
    "nav-about": "About",
    "nav-projects": "Projects",
    "nav-skills": "Skills",
    "nav-contact": "Contact",
    "hero-label": "Hello, I'm",
    "hero-desc": "3+ tahun membangun aplikasi web — dari sistem sekolah, e-commerce,<br class=\"br-desktop\" />hingga enterprise BUMN.",
    "hero-cta-projects": "Lihat Projects",
    "hero-cta-contact": "Hubungi Saya",
    "section-title-about": "Tentang Saya",
    "about-p1": "Software Developer dengan pengalaman profesional lebih dari <strong>3 tahun</strong> dalam pengembangan aplikasi web, mulai dari sistem informasi pendidikan, e-commerce, hingga aplikasi enterprise.",
    "about-p2": "Selama berkarier, saya telah terlibat dalam pengembangan aplikasi untuk institusi pendidikan, perusahaan swasta, dan <strong>BUMN</strong>. Pengalaman mencakup frontend dan backend, integrasi payment gateway, shipping provider, serta pengembangan berbasis <strong>microservice dan microfrontend</strong>.",
    "about-p3": "Saya terbiasa bekerja dalam lingkungan yang menerapkan <strong>SDLC terstruktur</strong>, code review, kolaborasi lintas tim, dan standar kualitas tinggi.",
    "project-desc-1": "Terlibat dalam pengembangan berbagai aplikasi internal dan publik PT Pegadaian menggunakan arsitektur <strong>microservice dan microfrontend</strong>, dalam lingkungan enterprise dengan SDLC terstruktur.",
    "sub-project-1-desc": "Pengembangan modul website resmi, termasuk fitur layanan Bank Emas.",
    "sub-project-2-desc": "Portal digital internal pegawai PT Pegadaian. Kontribusi pada modul microfrontend.",
    "sub-project-3-desc": "Platform administrasi dan operasional perkantoran digital: surat-menyurat, surat tugas, dan digitalisasi internal.",
    "project-desc-2": "Aplikasi psikotes digital yang digunakan oleh perusahaan untuk proses seleksi karyawan baru maupun evaluasi promosi jabatan, mencakup berbagai modul asesmen yang terstandarisasi.",
    "project-contrib-2-1": "Pengembangan platform assessment center berbasis web",
    "project-contrib-2-2": "Implementasi berbagai modul tes psikologi dan kompetensi secara digital",
    "project-contrib-2-3": "Mendukung proses seleksi karyawan dan evaluasi kenaikan pangkat",
    "project-desc-3": "Pengembangan dua sistem internal PT HKM, salah satu supplier resmi Telkomsel: Order Management System untuk mengelola penjualan produk Telkomsel, dan Warehouse Management System untuk operasional pergudangan.",
    "project-contrib-3-1": "Pengembangan Order Management System untuk produk Telkomsel seperti router, modem, dan kartu SIM",
    "project-contrib-3-2": "Integrasi payment gateway Midtrans dengan berbagai metode pembayaran, termasuk Virtual Account",
    "project-contrib-3-3": "Integrasi layanan pengiriman: AnterAja, SiCepat, dan GrabExpress",
    "project-contrib-3-4": "Pengembangan Warehouse Management System untuk pengelolaan stok dan operasional gudang",
    "project-desc-4": "Platform e-commerce sebagai kanal penjualan produk PT Erdigma Indonesia dengan fokus pada kebutuhan reseller.",
    "project-contrib-4-1": "Kontribusi pengembangan aplikasi e-commerce end-to-end",
    "project-contrib-4-2": "Pengembangan fitur frontend dan backend",
    "project-contrib-4-3": "Integrasi payment gateway iPaymu",
    "project-contrib-4-4": "Mendukung proses transaksi dari checkout hingga pembayaran",
    "project-title-5": "Sistem Ujian &amp; Rapor Digital",
    "project-desc-5": "Sistem informasi sekolah yang mendukung pelaksanaan ujian berbasis komputer serta pengelolaan nilai siswa, dengan fitur penilaian otomatis dan penyusunan rapor digital.",
    "project-contrib-5-1": "Mengembangkan sistem ujian online untuk siswa",
    "project-contrib-5-2": "Implementasi penilaian otomatis berdasarkan jawaban peserta",
    "project-contrib-5-3": "Modul pengelolaan nilai dan rapor siswa",
    "project-contrib-5-4": "Pengembangan fitur administrasi sekolah",
    "project-note": "Source code di bawah pengelolaan klien",
    "skills-intro": "Teknologi yang saya gunakan selama mengerjakan berbagai proyek profesional.",
    "contact-intro": "Terbuka untuk peluang baru, kolaborasi, atau sekadar ngobrol soal teknologi."
  },
  en: {
    "nav-about": "About",
    "nav-projects": "Projects",
    "nav-skills": "Skills",
    "nav-contact": "Contact",
    "hero-label": "Hello, I'm",
    "hero-desc": "3+ years building web applications — from school systems, e-commerce,<br class=\"br-desktop\" />to BUMN enterprises.",
    "hero-cta-projects": "View Projects",
    "hero-cta-contact": "Contact Me",
    "section-title-about": "About Me",
    "about-p1": "Software Developer with over <strong>3 years</strong> of professional experience in web application development, ranging from educational information systems, e-commerce, to enterprise applications.",
    "about-p2": "Throughout my career, I have been involved in developing applications for educational institutions, private companies, and <strong>state-owned enterprises (BUMN)</strong>. My experience covers frontend and backend, payment gateway and shipping provider integrations, as well as <strong>microservice and microfrontend</strong> based development.",
    "about-p3": "I am accustomed to working in environments that implement <strong>structured SDLC</strong>, code reviews, cross-team collaboration, and high quality standards.",
    "project-desc-1": "Involved in the development of various internal and public applications for PT Pegadaian using <strong>microservice and microfrontend</strong> architecture, within an enterprise environment with structured SDLC.",
    "sub-project-1-desc": "Development of the official website module, including the Bank Emas service feature.",
    "sub-project-2-desc": "Internal digital portal for PT Pegadaian employees. Contributed to the microfrontend module.",
    "sub-project-3-desc": "Digital office administration and operational platform: correspondence, assignment letters, and internal digitalization.",
    "project-desc-2": "A digital psychological test application used by companies for new employee selection processes and promotion evaluations, encompassing various standardized assessment modules.",
    "project-contrib-2-1": "Development of a web-based assessment center platform",
    "project-contrib-2-2": "Implementation of various psychological and competency test modules digitally",
    "project-contrib-2-3": "Supporting employee selection processes and promotion evaluations",
    "project-desc-3": "Development of two internal systems for PT HKM, an official Telkomsel supplier: Order Management System for managing Telkomsel product sales, and Warehouse Management System for warehouse operations.",
    "project-contrib-3-1": "Development of Order Management System for Telkomsel products such as routers, modems, and SIM cards",
    "project-contrib-3-2": "Midtrans payment gateway integration with various payment methods, including Virtual Accounts",
    "project-contrib-3-3": "Shipping service integrations: AnterAja, SiCepat, and GrabExpress",
    "project-contrib-3-4": "Development of Warehouse Management System for stock management and warehouse operations",
    "project-desc-4": "An e-commerce platform serving as a sales channel for PT Erdigma Indonesia products with a focus on reseller needs.",
    "project-contrib-4-1": "Contributed to end-to-end e-commerce application development",
    "project-contrib-4-2": "Development of frontend and backend features",
    "project-contrib-4-3": "iPaymu payment gateway integration",
    "project-contrib-4-4": "Supporting the transaction process from checkout to payment",
    "project-title-5": "Digital Exam &amp; Report Card System",
    "project-desc-5": "A school information system that supports computer-based exams and student grade management, featuring automatic grading and digital report card generation.",
    "project-contrib-5-1": "Developing an online exam system for students",
    "project-contrib-5-2": "Implementation of automatic grading based on participant answers",
    "project-contrib-5-3": "Student grade and report card management module",
    "project-contrib-5-4": "Development of school administration features",
    "project-note": "Source code managed by the client",
    "skills-intro": "Technologies I have used while working on various professional projects.",
    "contact-intro": "Open to new opportunities, collaborations, or just chatting about technology."
  }
};
